apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
#spec:
#  values:
#    global:
#      enabled: false
#      datacenter: aws-prod
#    client:
#      enabled: true
#      join:
#        - consul1-p.eu-west-1.impresa.pt
#        - consul2-p.eu-west-1.impresa.pt
#        - consul3-p.eu-west-1.impresa.pt
#      exposeGossipPorts: true
