apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
spec:
  values:
    server:
      ha:
        enabled: true
        replicas: 3
#    global:
#      enabled: false
#      datacenter: aws-prod
#    client:
#      enabled: true
#      join:
#        - consul1-p.eu-west-1.xxx
#        - consul2-p.eu-west-1.xxx
#        - consul3-p.eu-west-1.xxx
#      exposeGossipPorts: true
